credentials:
  usernames:
    Snehaunshu:
      email: snehaunshu@example.com
      name: Snehaunshu
      password: <hashed_password>
    Majid:
      email: majid@example.com
      name: Majid
      password: <hashed_password>
    Husam:
      email: husam@example.com
      name: Husam
      password: <hashed_password>
    Aaryan:
      email: aaryan@example.com
      name: Aaryan
      password: <hashed_password>
    Drashti:
      email: drashti@example.com
      name: Drashti
      password: <hashed_password>
    Sai:
      email: sai@example.com
      name: Sai
      password: <hashed_password>
    Keane:
      email: keane@example.com
      name: Keane
      password: <hashed_password>
    Marshal:
      email: marshal@example.com
      name: Marshal
      password: <hashed_password>
    Sanjay:
      email: sanjay@example.com
      name: Sanjay
      password: <hashed_password>
cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails: []
